### ISSUE TITLE
SPIKE: Choose a Test Coverage Tool

### ISSUE THREAD

**Issue by zeonin** [MSUTeam1/unbanner#22] opened 2017-09-05 18:06 UTC
As Team1, we want to know the best test coverage tool. By the end of the sprint, we expect a list of test coverage tool options, a list of pros and cons for each one, and a decision for which tool we will use.

AC:
* A list of possible Test Coverage Tool options
* A few major pros and cons of each
* A recommendation for the assignee's preferred tool

**Comment by toasterbrain** [comment] 2017-09-07 17:05
I am reasonably sure this is a duplicate of #20 (Add Junit for test coverage) and should be removed.

**Comment by toasterbrain** [comment] 2017-09-08 19:02
chat on the class chat channel said if we were using an ide our test coverage tool was probably integrated with that. is anyone not using an ide?

**Comment by cblanto7** [comment] 2017-09-08 19:24
I don't use an IDE. 
However, I am willing to use an IDE (either eclipse or IntelliJ) if it makes it easier for everyone to be on the same page with things.

**Comment by toasterbrain** [comment] 2017-09-16 21:47
I'm pretty sure the 4 of us that are going to use an IDE are using Intelllij. This integrates junit tests.

**Comment by cblanto7** [comment] 2017-09-17 00:37
To be even more specific we will be using the spring package 

> org.springframework.boot:spring-boot-starter-test

which imports both Spring Boot test modules as well has JUnit, AssertJ, Hamcrest, Mocktio and a number of other useful libraries.

see [https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html) for more details.

**Comment by toasterbrain** [comment] 2017-09-19 19:12
okay. looks like we have finished this card. I didn't know it had all those test libraries in it.

**Closed by toasterbrain** 2017-09-19 19:12 UTC
